version: '3.6'

services:
  shadowsocks:
    image: dcatfly/shadowsocks-libev-config
    volumes:
      - "./configs/ss.json:/etc/shadowsocks/config.json"
    ports:
      - "12137:12137"
    environment:
      - CONFIG=/etc/shadowsocks/config.json
    restart: always