version: '3.6'

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "12137:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=password
    restart: always